In [10]:
import pandas as pd
import numpy as np
from IPython.display import display, Markdown

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

df = pd.read_csv("train.csv")


def section(title):
    display(Markdown(f"## {title}"))


section("Dataset overview")

overview = pd.DataFrame({
    "metric": [
        "Rows",
        "Columns",
        "Total cells",
        "Memory usage MB"
    ],
    "value": [
        df.shape[0],
        df.shape[1],
        df.shape[0] * df.shape[1],
        round(df.memory_usage(deep=True).sum() / 1024**2, 2)
    ]
})

display(overview)


section("Column types")

dtype_summary = df.dtypes.value_counts().reset_index()
dtype_summary.columns = ["dtype", "count"]

display(dtype_summary)

column_summary = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "non_null_count": df.notnull().sum().values,
    "null_count": df.isnull().sum().values,
    "missing_%": (df.isnull().mean().values * 100),
    "unique_count": df.nunique(dropna=True).values,
    "unique_%": (df.nunique(dropna=True).values / len(df) * 100)
})

display(column_summary)


section("Missing values")

missing_df = column_summary[
    ["column", "null_count", "missing_%"]
].sort_values("missing_%", ascending=False)

missing_overview = pd.DataFrame({
    "metric": [
        "Total missing cells",
        "Total missing %",
        "Rows with at least one missing value",
        "Rows with at least one missing value %"
    ],
    "value": [
        df.isnull().sum().sum(),
        round(df.isnull().sum().sum() / (df.shape[0] * df.shape[1]) * 100, 2),
        df.isnull().any(axis=1).sum(),
        round(df.isnull().any(axis=1).mean() * 100, 2)
    ]
})

display(missing_overview)
display(missing_df)


section("Columns grouped by missingness")

missing_groups = pd.DataFrame({
    "group": [
        "More than 90% missing",
        "More than 50% missing",
        "Between 10% and 50% missing",
        "No missing values"
    ],
    "columns": [
        missing_df[missing_df["missing_%"] > 90]["column"].tolist(),
        missing_df[missing_df["missing_%"] > 50]["column"].tolist(),
        missing_df[(missing_df["missing_%"] >= 10) & (missing_df["missing_%"] <= 50)]["column"].tolist(),
        missing_df[missing_df["null_count"] == 0]["column"].tolist()
    ]
})

display(missing_groups)


section("Empty strings and whitespace")

object_cols = df.select_dtypes(include="object").columns

empty_string_info = []

for col in object_cols:
    empty_strings = (df[col] == "").sum()
    empty_or_whitespace = df[col].astype(str).str.strip().eq("").sum()

    if empty_strings > 0 or empty_or_whitespace > 0:
        empty_string_info.append({
            "column": col,
            "empty_strings": empty_strings,
            "empty_or_whitespace": empty_or_whitespace
        })

empty_string_df = pd.DataFrame(empty_string_info)

if len(empty_string_df) > 0:
    display(empty_string_df)
else:
    display(pd.DataFrame({"result": ["No empty or whitespace-only strings detected"]}))


section("Duplicates")

duplicates_df = pd.DataFrame({
    "check": [
        "Fully duplicated rows",
        "Duplicated Unique Key values" if "Unique Key" in df.columns else "Duplicated Unique Key values"
    ],
    "count": [
        df.duplicated().sum(),
        df["Unique Key"].duplicated().sum() if "Unique Key" in df.columns else np.nan
    ]
})

display(duplicates_df)


section("Cardinality analysis")

cardinality_df = pd.DataFrame({
    "column": df.columns,
    "unique_count": df.nunique(dropna=True).values,
    "unique_%": df.nunique(dropna=True).values / len(df) * 100,
    "dtype": df.dtypes.astype(str).values
}).sort_values("unique_count", ascending=False)

display(cardinality_df)


section("Cardinality groups")

cardinality_groups = pd.DataFrame({
    "group": [
        "High-cardinality columns, more than 90% unique",
        "Low-cardinality columns, 10 or fewer unique values"
    ],
    "columns": [
        cardinality_df[cardinality_df["unique_%"] > 90]["column"].tolist(),
        cardinality_df[cardinality_df["unique_count"] <= 10]["column"].tolist()
    ]
})

display(cardinality_groups)


section("Constant and near-constant columns")

constant_cols = cardinality_df[cardinality_df["unique_count"] <= 1]["column"].tolist()

near_constant_info = []

for col in df.columns:
    top_freq = df[col].value_counts(dropna=False, normalize=True).head(1)

    if len(top_freq) > 0:
        most_common_pct = top_freq.iloc[0] * 100

        if most_common_pct > 95:
            near_constant_info.append({
                "column": col,
                "most_common_value": top_freq.index[0],
                "most_common_%": most_common_pct
            })

near_constant_df = pd.DataFrame(near_constant_info)

constant_summary = pd.DataFrame({
    "type": ["Constant columns"],
    "columns": [constant_cols]
})

display(constant_summary)

if len(near_constant_df) > 0:
    display(near_constant_df.sort_values("most_common_%", ascending=False))
else:
    display(pd.DataFrame({"result": ["No near-constant columns detected"]}))


section("Numeric columns")

numeric_cols = df.select_dtypes(include=np.number).columns

numeric_summary = df[numeric_cols].describe().T
display(numeric_summary)


section("Numeric outliers using IQR method")

outlier_info = []

for col in numeric_cols:
    series = df[col].dropna()

    if len(series) == 0:
        continue

    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    if iqr == 0:
        continue

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = ((series < lower_bound) | (series > upper_bound)).sum()

    outlier_info.append({
        "column": col,
        "outlier_count": outliers,
        "outlier_%": outliers / len(series) * 100,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "min": series.min(),
        "max": series.max()
    })

outlier_df = pd.DataFrame(outlier_info)

if len(outlier_df) > 0:
    display(outlier_df.sort_values("outlier_%", ascending=False))
else:
    display(pd.DataFrame({"result": ["No numeric outliers detected"]}))


section("Object and categorical columns")

categorical_summary = []

for col in object_cols:
    value_counts = df[col].value_counts(dropna=False)
    top_value = value_counts.index[0] if len(value_counts) > 0 else None
    top_count = value_counts.iloc[0] if len(value_counts) > 0 else 0
    top_pct = top_count / len(df) * 100

    categorical_summary.append({
        "column": col,
        "unique_count": df[col].nunique(dropna=True),
        "missing_%": df[col].isnull().mean() * 100,
        "top_value": top_value,
        "top_value_%": top_pct
    })

categorical_summary_df = pd.DataFrame(categorical_summary)
categorical_summary_df = categorical_summary_df.sort_values("unique_count", ascending=False)

display(categorical_summary_df)


section("Top values for low-cardinality columns")

low_card_cols = cardinality_df[
    (cardinality_df["unique_count"] <= 20) &
    (cardinality_df["unique_count"] > 1)
]["column"].tolist()

top_values_tables = []

for col in low_card_cols:
    temp = df[col].value_counts(dropna=False).head(10).reset_index()
    temp.columns = ["value", "count"]
    temp.insert(0, "column", col)
    top_values_tables.append(temp)

if len(top_values_tables) > 0:
    top_values_df = pd.concat(top_values_tables, ignore_index=True)
    display(top_values_df)
else:
    display(pd.DataFrame({"result": ["No low-cardinality columns found"]}))


section("Date columns check")

possible_date_cols = [
    col for col in df.columns
    if "date" in col.lower() or "time" in col.lower()
]

date_info = []

for col in possible_date_cols:
    parsed = pd.to_datetime(df[col], errors="coerce")
    invalid_count = parsed.isnull().sum() - df[col].isnull().sum()

    date_info.append({
        "column": col,
        "current_dtype": df[col].dtype,
        "missing_before_parsing": df[col].isnull().sum(),
        "invalid_dates_after_parsing": invalid_count,
        "min_date": parsed.min() if parsed.notnull().sum() > 0 else None,
        "max_date": parsed.max() if parsed.notnull().sum() > 0 else None
    })

date_info_df = pd.DataFrame(date_info)
display(date_info_df)


section("Created and closed date consistency")

if "Created Date" in df.columns and "Closed Date" in df.columns:
    created = pd.to_datetime(df["Created Date"], errors="coerce")
    closed = pd.to_datetime(df["Closed Date"], errors="coerce")

    resolution_time_hours = (closed - created).dt.total_seconds() / 3600

    consistency_df = pd.DataFrame({
        "metric": [
            "Invalid Created Date values",
            "Invalid Closed Date values",
            "Missing Closed Date values",
            "Rows where Closed Date is before Created Date",
            "Negative resolution times",
            "Resolution times greater than 1 year"
        ],
        "value": [
            created.isnull().sum() - df["Created Date"].isnull().sum(),
            closed.isnull().sum() - df["Closed Date"].isnull().sum(),
            closed.isnull().sum(),
            (closed < created).sum(),
            (resolution_time_hours < 0).sum(),
            (resolution_time_hours > 24 * 365).sum()
        ]
    })

    display(consistency_df)

    resolution_summary = resolution_time_hours.describe().reset_index()
    resolution_summary.columns = ["statistic", "resolution_time_hours"]

    display(resolution_summary)


section("Geographic columns check")

geo_cols = ["Latitude", "Longitude", "Location", "Incident Zip", "BBL"]

geo_info = []

for col in geo_cols:
    if col in df.columns:
        row = {
            "column": col,
            "dtype": df[col].dtype,
            "missing_%": round(df[col].isnull().mean() * 100, 2),
            "unique_values": df[col].nunique(dropna=True),
            "non_numeric_after_conversion": None,
            "min_after_conversion": None,
            "max_after_conversion": None
        }

        if col in ["Latitude", "Longitude"]:
            converted = pd.to_numeric(
                df[col].astype(str).str.replace(",", ".", regex=False),
                errors="coerce"
            )

            row["non_numeric_after_conversion"] = converted.isnull().sum() - df[col].isnull().sum()
            row["min_after_conversion"] = converted.min()
            row["max_after_conversion"] = converted.max()

        geo_info.append(row)

geo_info_df = pd.DataFrame(geo_info)
display(geo_info_df)


section("Potential data leakage columns")

leakage_keywords = ["closed", "resolution", "status", "due"]

potential_leakage_cols = [
    col for col in df.columns
    if any(keyword in col.lower() for keyword in leakage_keywords)
]

leakage_df = pd.DataFrame({
    "potential_leakage_column": potential_leakage_cols
})

display(leakage_df)


section("Final diagnostic summary")

final_summary = pd.DataFrame({
    "metric": [
        "Rows",
        "Columns",
        "Object columns",
        "Numeric columns",
        "Columns with more than 50% missing",
        "Columns with 10% to 50% missing",
        "High-cardinality columns",
        "Constant columns",
        "Fully duplicated rows",
        "Rows with missing Closed Date"
    ],
    "value": [
        n_rows,
        n_cols,
        len(object_cols),
        len(numeric_cols),
        len(missing_df[missing_df["missing_%"] > 50]),
        len(missing_df[(missing_df["missing_%"] >= 10) & (missing_df["missing_%"] <= 50)]),
        len(cardinality_df[cardinality_df["unique_%"] > 90]),
        len(constant_cols),
        df.duplicated().sum(),
        df["Closed Date"].isnull().sum() if "Closed Date" in df.columns else None
    ]
})

display(final_summary)

issues = pd.DataFrame({
    "main_issue": [
        "Many columns are stored as object dtype.",
        "Some columns require date parsing.",
        "Some columns have high missingness.",
        "Some columns may be ID-like or too high-cardinality for direct modelling.",
        "Geographic columns may require type conversion or parsing.",
        "Closed Date may create missing target values or data leakage depending on the modelling objective."
    ]
})

display(issues)

## Dataset overview

            metric      value
0             Rows   110930.0
1          Columns       41.0
2      Total cells  4548130.0
3  Memory usage MB      234.7

## Column types

     dtype  count
0   object     36
1  float64      3
2    int64      2

,column,dtype,non_null_count,null_count,missing_%,unique_count,unique_%
0,Unnamed: 0,int64,110930,0,0.000000,110930,100.000000
1,Unique Key,int64,110930,0,0.000000,110930,100.000000
2,Created Date,object,110930,0,0.000000,95296,85.906427
3,Closed Date,object,91738,19192,17.301001,73517,66.273326
4,Agency,object,110930,0,0.000000,15,0.013522
5,Agency Name,object,110930,0,0.000000,15,0.013522
6,Problem (formerly Complaint Type),object,110930,0,0.000000,163,0.146940
7,Problem Detail (formerly Descriptor),object,109098,1832,1.651492,700,0.631029
8,Additional Details,object,41038,69892,63.005499,577,0.520148
9,Location Type,object,93679,17251,15.551249,106,0.095556
10,Incident Zip,float64,109894,1036,0.933922,222,0.200126
11,Incident Address,object,105945,4985,4.493825,52948,47.731002
12,Street Name,object,105940,4990,4.498332,6210,5.598125
13,Cross Street 1,object,78973,31957,28.808257,7199,6.489678
14,Cross Street 2,object,78999,31931,28.784819,7077,6.379699
15,Intersection Street 1,object,74027,36903,33.266925,5119,4.614622
16,Intersection Street 2,object,74080,36850,33.219147,5148,4.640764
17,Address Type,object,110292,638,0.575137,5,0.004507
18,City,object,105175,5755,5.187956,54,0.048679
19,Landmark,object,64765,46165,41.616335,4636,4.179212
20,Facility Type,object,363,110567,99.672767,1,0.000901
21,Community Board,object,110930,0,0.000000,77,0.069413
22,Council District,float64,106425,4505,4.061120,51,0.045975
23,Police Precinct,object,110930,0,0.000000,78,0.070315
24,BBL,float64,95355,15575,14.040386,43815,39.497882
25,Borough,object,110930,0,0.000000,6,0.005409
26,X Coordinate (State Plane),object,106975,3955,3.565311,38683,34.871541
27,Y Coordinate (State Plane),object,106988,3942,3.553592,43024,38.784819
28,Open Data Channel Type,object,110930,0,0.000000,4,0.003606
29,Park Facility Name,object,110858,72,0.064906,5,0.004507
30,Park Borough,object,110930,0,0.000000,6,0.005409
31,Vehicle Type,object,5372,105558,95.157306,6,0.005409
32,Taxi Company Borough,object,70,110860,99.936897,5,0.004507
33,Taxi Pick Up Location,object,1183,109747,98.933562,828,0.746417
34,Bridge Highway Name,object,594,110336,99.464527,55,0.049581
35,Bridge Highway Direction,object,372,110558,99.664653,72,0.064906
36,Road Ramp,object,350,110580,99.684486,36,0.032453
37,Bridge Highway Segment,object,593,110337,99.465429,229,0.206436
38,Latitude,object,106973,3957,3.567114,55255,49.810691
39,Longitude,object,106973,3957,3.567114,55255,49.810691
40,Location,object,106973,3957,3.567114,55255,49.810691

## Missing values

                                   metric      value
0                     Total missing cells  1227840.0
1                         Total missing %       27.0
2    Rows with at least one missing value   110930.0
3  Rows with at least one missing value %      100.0

                                  column  null_count  missing_%
32                  Taxi Company Borough      110860  99.936897
36                             Road Ramp      110580  99.684486
20                         Facility Type      110567  99.672767
35              Bridge Highway Direction      110558  99.664653
37                Bridge Highway Segment      110337  99.465429
34                   Bridge Highway Name      110336  99.464527
33                 Taxi Pick Up Location      109747  98.933562
31                          Vehicle Type      105558  95.157306
8                     Additional Details       69892  63.005499
19                              Landmark       46165  41.616335
15                 Intersection Street 1       36903  33.266925
16                 Intersection Street 2       36850  33.219147
13                        Cross Street 1       31957  28.808257
14                        Cross Street 2       31931  28.784819
3                            Closed Date       19192  17.301001
9                          Location Type       17251  15.551249
24                                   BBL       15575  14.040386
18                                  City        5755   5.187956
12                           Street Name        4990   4.498332
11                      Incident Address        4985   4.493825
22                      Council District        4505   4.061120
38                              Latitude        3957   3.567114
39                             Longitude        3957   3.567114
40                              Location        3957   3.567114
26            X Coordinate (State Plane)        3955   3.565311
27            Y Coordinate (State Plane)        3942   3.553592
7   Problem Detail (formerly Descriptor)        1832   1.651492
10                          Incident Zip        1036   0.933922
17                          Address Type         638   0.575137
29                    Park Facility Name          72   0.064906
23                       Police Precinct           0   0.000000
2                           Created Date           0   0.000000
4                                 Agency           0   0.000000
5                            Agency Name           0   0.000000
6      Problem (formerly Complaint Type)           0   0.000000
1                             Unique Key           0   0.000000
25                               Borough           0   0.000000
21                       Community Board           0   0.000000
30                          Park Borough           0   0.000000
28                Open Data Channel Type           0   0.000000
0                             Unnamed: 0           0   0.000000

## Columns grouped by missingness

,group,columns
0,More than 90% missing,"[Taxi Company Borough, Road Ramp, Facility Type, Bridge Highway Direction, Bridge Highway Segment, Bridge Highway Name, Taxi Pick Up Location, Vehicle Type]"
1,More than 50% missing,"[Taxi Company Borough, Road Ramp, Facility Type, Bridge Highway Direction, Bridge Highway Segment, Bridge Highway Name, Taxi Pick Up Location, Vehicle Type, Additional Details]"
2,Between 10% and 50% missing,"[Landmark, Intersection Street 1, Intersection Street 2, Cross Street 1, Cross Street 2, Closed Date, Location Type, BBL]"
3,No missing values,"[Police Precinct, Created Date, Agency, Agency Name, Problem (formerly Complaint Type), Unique Key, Borough, Community Board, Park Borough, Open Data Channel Type, Unnamed: 0]"

## Empty strings and whitespace

                                         result
0  No empty or whitespace-only strings detected

## Duplicates

                          check  count
0         Fully duplicated rows      0
1  Duplicated Unique Key values      0

## Cardinality analysis

                                  column  unique_count    unique_%    dtype
0                             Unnamed: 0        110930  100.000000    int64
1                             Unique Key        110930  100.000000    int64
2                           Created Date         95296   85.906427   object
3                            Closed Date         73517   66.273326   object
39                             Longitude         55255   49.810691   object
38                              Latitude         55255   49.810691   object
40                              Location         55255   49.810691   object
11                      Incident Address         52948   47.731002   object
24                                   BBL         43815   39.497882  float64
27            Y Coordinate (State Plane)         43024   38.784819   object
26            X Coordinate (State Plane)         38683   34.871541   object
13                        Cross Street 1          7199    6.489678   object
14                        Cross Street 2          7077    6.379699   object
12                           Street Name          6210    5.598125   object
16                 Intersection Street 2          5148    4.640764   object
15                 Intersection Street 1          5119    4.614622   object
19                              Landmark          4636    4.179212   object
33                 Taxi Pick Up Location           828    0.746417   object
7   Problem Detail (formerly Descriptor)           700    0.631029   object
8                     Additional Details           577    0.520148   object
37                Bridge Highway Segment           229    0.206436   object
10                          Incident Zip           222    0.200126  float64
6      Problem (formerly Complaint Type)           163    0.146940   object
9                          Location Type           106    0.095556   object
23                       Police Precinct            78    0.070315   object
21                       Community Board            77    0.069413   object
35              Bridge Highway Direction            72    0.064906   object
34                   Bridge Highway Name            55    0.049581   object
18                                  City            54    0.048679   object
22                      Council District            51    0.045975  float64
36                             Road Ramp            36    0.032453   object
4                                 Agency            15    0.013522   object
5                            Agency Name            15    0.013522   object
30                          Park Borough             6    0.005409   object
31                          Vehicle Type             6    0.005409   object
25                               Borough             6    0.005409   object
32                  Taxi Company Borough             5    0.004507   object
29                    Park Facility Name             5    0.004507   object
17                          Address Type             5    0.004507   object
28                Open Data Channel Type             4    0.003606   object
20                         Facility Type             1    0.000901   object

## Cardinality groups

,group,columns
0,"High-cardinality columns, more than 90% unique","[Unnamed: 0, Unique Key]"
1,"Low-cardinality columns, 10 or fewer unique values","[Park Borough, Vehicle Type, Borough, Taxi Company Borough, Park Facility Name, Address Type, Open Data Channel Type, Facility Type]"

## Constant and near-constant columns

               type          columns
0  Constant columns  [Facility Type]

                     column most_common_value  most_common_%
3      Taxi Company Borough               NaN      99.936897
1        Park Facility Name       Unspecified      99.928784
7                 Road Ramp               NaN      99.684486
0             Facility Type               NaN      99.672767
6  Bridge Highway Direction               NaN      99.664653
8    Bridge Highway Segment               NaN      99.465429
5       Bridge Highway Name               NaN      99.464527
4     Taxi Pick Up Location               NaN      98.933562
2              Vehicle Type               NaN      95.157306

## Numeric columns

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,110930.0,5.546450e+04,3.202288e+04,0.000000e+00,2.773225e+04,5.546450e+04,8.319675e+04,1.109290e+05
Unique Key,110930.0,6.860728e+07,4.261134e+04,6.852576e+07,6.857046e+07,6.860722e+07,6.864369e+07,6.871651e+07
Incident Zip,109894.0,1.082228e+04,5.916326e+02,1.000000e+04,1.045200e+04,1.120100e+04,1.123500e+04,9.210800e+04
Council District,106425.0,2.436116e+01,1.430869e+01,1.000000e+00,1.200000e+01,2.400000e+01,3.600000e+01,5.100000e+01
BBL,95355.0,2.724757e+09,1.156364e+09,1.000020e+09,2.027650e+09,3.017960e+09,4.006320e+09,5.200430e+09

## Numeric outliers using IQR method

,column,outlier_count,outlier_%,lower_bound,upper_bound,min,max
2,Incident Zip,2,0.00182,9277.5,1.240950e+04,1.000000e+04,9.210800e+04
0,Unnamed: 0,0,0.00000,-55464.5,1.663935e+05,0.000000e+00,1.109290e+05
1,Unique Key,0,0.00000,68460624.0,6.875353e+07,6.852576e+07,6.871651e+07
3,Council District,0,0.00000,-24.0,7.200000e+01,1.000000e+00,5.100000e+01
4,BBL,0,0.00000,-940354497.5,6.974325e+09,1.000020e+09,5.200430e+09

## Object and categorical columns

,column,unique_count,missing_%,top_value,top_value_%
0,Created Date,95296,0.000000,04/13/2026 12:50:01 PM,0.011719
1,Closed Date,73517,17.301001,NaN,17.301001
34,Longitude,55255,3.567114,NaN,3.567114
33,Latitude,55255,3.567114,NaN,3.567114
35,Location,55255,3.567114,NaN,3.567114
8,Incident Address,52948,4.493825,NaN,4.493825
22,Y Coordinate (State Plane),43024,3.553592,NaN,3.553592
21,X Coordinate (State Plane),38683,3.565311,NaN,3.565311
10,Cross Street 1,7199,28.808257,NaN,28.808257
11,Cross Street 2,7077,28.784819,NaN,28.784819
9,Street Name,6210,4.498332,NaN,4.498332
13,Intersection Street 2,5148,33.219147,NaN,33.219147
12,Intersection Street 1,5119,33.266925,NaN,33.266925
16,Landmark,4636,41.616335,NaN,41.616335
28,Taxi Pick Up Location,828,98.933562,NaN,98.933562
5,Problem Detail (formerly Descriptor),700,1.651492,Loud Music/Party,10.419183
6,Additional Details,577,63.005499,NaN,63.005499
32,Bridge Highway Segment,229,99.465429,NaN,99.465429
4,Problem (formerly Complaint Type),163,0.000000,Illegal Parking,16.239070
7,Location Type,106,15.551249,Street/Sidewalk,30.475976
19,Police Precinct,78,0.000000,Precinct 47,2.920761
18,Community Board,77,0.000000,12 MANHATTAN,2.959524
30,Bridge Highway Direction,72,99.664653,NaN,99.664653
29,Bridge Highway Name,55,99.464527,NaN,99.464527
15,City,54,5.187956,BROOKLYN,28.489137
31,Road Ramp,36,99.684486,NaN,99.684486
3,Agency Name,15,0.000000,New York City Police Department,44.394663
2,Agency,15,0.000000,NYPD,44.394663
25,Park Borough,6,0.000000,BROOKLYN,29.738574
26,Vehicle Type,6,95.157306,NaN,95.157306
20,Borough,6,0.000000,BROOKLYN,29.738574
24,Park Facility Name,5,0.064906,Unspecified,99.928784
27,Taxi Company Borough,5,99.936897,NaN,99.936897
14,Address Type,5,0.575137,ADDRESS,87.519156
23,Open Data Channel Type,4,0.000000,ONLINE,45.255567
17,Facility Type,1,99.672767,NaN,99.672767

## Top values for low-cardinality columns

,column,value,count
0,Agency,NYPD,49247
1,Agency,HPD,22690
2,Agency,DOT,10523
3,Agency,DSNY,9354
4,Agency,DEP,5660
5,Agency,DOB,3624
6,Agency,DPR,2855
7,Agency,DOHMH,2472
8,Agency,DHS,1644
9,Agency,TLC,1204
10,Agency Name,New York City Police Department,49247
11,Agency Name,Department of Housing Preservation and Development,22690
12,Agency Name,Department of Transportation,10523
13,Agency Name,Department of Sanitation,9354
14,Agency Name,Department of Environmental Protection,5660
15,Agency Name,Department of Buildings,3624
16,Agency Name,Department of Parks and Recreation,2855
17,Agency Name,Department of Health and Mental Hygiene,2472
18,Agency Name,Department of Homeless Services,1644
19,Agency Name,Taxi and Limousine Commission,1204
20,Park Borough,BROOKLYN,32989
21,Park Borough,QUEENS,28148
22,Park Borough,BRONX,22809
23,Park Borough,MANHATTAN,22537
24,Park Borough,STATEN ISLAND,4330
25,Park Borough,Unspecified,117
26,Vehicle Type,NaN,105558
27,Vehicle Type,Car,3389
28,Vehicle Type,SUV,611
29,Vehicle Type,Other,602
30,Vehicle Type,Van,413
31,Vehicle Type,Truck,322
32,Vehicle Type,Car Service,35
33,Borough,BROOKLYN,32989
34,Borough,QUEENS,28148
35,Borough,BRONX,22809
36,Borough,MANHATTAN,22537
37,Borough,STATEN ISLAND,4330
38,Borough,Unspecified,117
39,Taxi Company Borough,NaN,110860
40,Taxi Company Borough,MANHATTAN,21
41,Taxi Company Borough,QUEENS,20
42,Taxi Company Borough,BROOKLYN,12
43,Taxi Company Borough,BRONX,10
44,Taxi Company Borough,STATEN ISLAND,7
45,Park Facility Name,Unspecified,110851
46,Park Facility Name,NaN,72
47,Park Facility Name,Isham Park,4
48,Park Facility Name,MacDonald Park,1
49,Park Facility Name,Sarah J.S. Tompkins Garnet Playground,1
50,Park Facility Name,Forest Park,1
51,Address Type,ADDRESS,97085
52,Address Type,INTERSECTION,8778
53,Address Type,BLOCKFACE,3594
54,Address Type,PLACE,798
55,Address Type,NaN,638
56,Address Type,PLACENAME,37
57,Open Data Channel Type,ONLINE,50202
58,Open Data Channel Type,PHONE,26031
59,Open Data Channel Type,MOBILE,22824
60,Open Data Channel Type,UNKNOWN,11873

## Date columns check

,column,current_dtype,missing_before_parsing,invalid_dates_after_parsing,min_date,max_date
0,Created Date,object,0,0,2026-04-01 17:48:15,2026-04-15 17:48:08
1,Closed Date,object,19192,0,2026-03-30 08:25:00,2026-04-19 01:35:00

## Created and closed date consistency

                                          metric  value
0                    Invalid Created Date values      0
1                     Invalid Closed Date values      0
2                     Missing Closed Date values  19192
3  Rows where Closed Date is before Created Date     12
4                      Negative resolution times     12
5           Resolution times greater than 1 year      0

  statistic  resolution_time_hours
0     count           91738.000000
1      mean              26.598295
2       std              53.040171
3       min            -168.066667
4       25%               0.829444
5       50%               3.160972
6       75%              25.215278
7       max             394.927778

## Geographic columns check

,column,dtype,missing_%,unique_values,non_numeric_after_conversion,min_after_conversion,max_after_conversion
0,Latitude,object,3.57,55255,0.0,40.498886,40.912828
1,Longitude,object,3.57,55255,0.0,-74.253219,-73.700730
2,Location,object,3.57,55255,NaN,NaN,NaN
3,Incident Zip,float64,0.93,222,NaN,NaN,NaN
4,BBL,float64,14.04,43815,NaN,NaN,NaN

## Potential data leakage columns

  potential_leakage_column
0              Closed Date

## Final diagnostic summary

                               metric   value
0                                Rows  110930
1                             Columns      41
2                      Object columns      36
3                     Numeric columns       5
4  Columns with more than 50% missing       9
5     Columns with 10% to 50% missing       8
6            High-cardinality columns       2
7                    Constant columns       1
8               Fully duplicated rows       0
9       Rows with missing Closed Date   19192

                                                                                           main_issue
0                                                            Many columns are stored as object dtype.
1                                                                  Some columns require date parsing.
2                                                                 Some columns have high missingness.
3                           Some columns may be ID-like or too high-cardinality for direct modelling.
4                                          Geographic columns may require type conversion or parsing.
5  Closed Date may create missing target values or data leakage depending on the modelling objective.