In [4]:

# 1) setup

%run "./03_preprocessing.ipynb"

import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

required_objects = [
    "X_train",
    "y_train",
    "X_test"
]

for obj in required_objects:
    if obj not in globals():
        raise NameError(
            f"{obj} does not exist. Run Notebook 3 before running this notebook."
        )

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)

train shape: (110930, 41)
test shape: (27733, 40)
target
1    68085
0    42845
Name: count, dtype: int64
target
1    0.6138
0    0.3862
Name: proportion, dtype: float64
train processed shape: (110930, 42)
test processed shape: (27733, 41)
dropped columns:
['Facility Type', 'X Coordinate (State Plane)', 'Y Coordinate (State Plane)', 'Vehicle Type', 'Taxi Company Borough', 'Taxi Pick Up Location', 'Bridge Highway Name', 'Bridge Highway Direction', 'Road Ramp', 'Bridge Highway Segment']
train missing values: 0
test missing values: 0
temporal features added: ['created_hour_sin', 'created_hour_cos', 'created_day_sin', 'created_day_cos', 'created_month_sin', 'created_month_cos', 'created_is_business_hour', 'created_is_night']
geographic features added: ['is_manhattan', 'is_brooklyn', 'is_queens', 'is_bronx', 'is_staten_island', 'incident_zip_group', 'distance_from_nyc_center', 'latitude_longitude_interaction']
count-encoded features added: ['Agency_frequency', 'Agency Name_frequency', 'Problem (formerly Complaint Type)_frequency', 'Borough_frequency', 'Incident Zip_frequency', 'incident_zip_group_frequency']
interaction features added: ['weekend_night_interaction', 'business_hour_weekday_interaction', 'borough_weekend_interaction']
one-hot columns:
['Agency', 'Agency Name', 'Address Type', 'Borough', 'Open Data Channel Type', 'Park Facility Name', 'Park Borough', 'created_part_of_day', 'incident_zip_group']
label-encoded columns:
['Problem (formerly Complaint Type)', 'Problem Detail (formerly Descriptor)', 'Additional Details', 'Location Type', 'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2', 'Intersection Street 1', 'Intersection Street 2', 'City', 'Landmark', 'Community Board', 'Police Precinct']
train shape after encoding: (110930, 125)
test shape after encoding: (27733, 120)
X_train shape: (110930, 124)
y_train shape: (110930,)
X_test shape: (27733, 124)
Cell 10.1 — general feature engineering summary
engineered features before encoding: 25
engineered features visible before categorical encoding: 25
engineered features visible after categorical encoding: 40
final X_train shape: (110930, 124)
final X_test shape: (27733, 124)

Cell 10.2 — preview of engineered features before categorical encoding

,row_0,row_1,row_2,row_3,row_4
created_hour_sin,0.866025,-0.707107,0.0,0.0,0.707107
created_hour_cos,-0.5,-0.707107,-1.0,-1.0,-0.707107
created_day_sin,0.781831,0.433884,-0.781831,-0.433884,0.433884
created_day_cos,0.62349,-0.900969,0.62349,-0.900969,-0.900969
created_month_sin,0.866025,0.866025,0.866025,0.866025,0.866025
created_month_cos,-0.5,-0.5,-0.5,-0.5,-0.5
created_is_business_hour,0,1,1,1,1
created_is_night,0,0,0,0,0
is_manhattan,1,1,0,0,1
is_brooklyn,0,0,1,0,0
is_queens,0,0,0,0,0
is_bronx,0,0,0,1,0
is_staten_island,0,0,0,0,0
incident_zip_group,100,100,112,104,100
distance_from_nyc_center,0.034187,0.098122,0.049435,0.167399,0.038895
latitude_longitude_interaction,-3015.54017,-3017.777497,-3009.327758,-3019.399199,-3014.048617
Agency_frequency,0.204543,0.204543,0.084323,0.032669,0.204543
Agency Name_frequency,0.204543,0.204543,0.084323,0.032669,0.204543
Problem (formerly Complaint Type)_frequency,0.069918,0.069918,0.010646,0.001767,0.008555
Borough_frequency,0.203164,0.203164,0.297386,0.205616,0.203164
Incident Zip_frequency,0.007239,0.007888,0.008203,0.01336,0.00595
incident_zip_group_frequency,0.195213,0.195213,0.305337,0.205201,0.195213
weekend_night_interaction,0,0,0,0,0
business_hour_weekday_interaction,0,1,0,1,1
borough_weekend_interaction,0.0,0.0,0.297386,0.0,0.0

Cell 10.3 — target distribution used for supervised learning

   target  count  percentage
0       1  68085       61.38
1       0  42845       38.62

Cell 10.4 — feature quality check after preprocessing and encoding

,missing_values,unique_values,dtype
latitude_longitude_interaction,0,55256,float64
distance_from_nyc_center,0,55256,float64
Longitude,0,55255,float64
Latitude,0,55255,float64
Incident Address,0,52949,int64
BBL,0,43815,float64
Cross Street 1,0,7200,int64
Cross Street 2,0,7078,int64
Street Name,0,6211,int64
Intersection Street 2,0,5149,int64
Intersection Street 1,0,5120,int64
Landmark,0,4637,int64
Problem Detail (formerly Descriptor),0,701,int64
Additional Details,0,578,int64
Incident Zip,0,222,float64
Incident Zip_frequency,0,178,float64
Problem (formerly Complaint Type),0,163,int64
Problem (formerly Complaint Type)_frequency,0,119,float64
Location Type,0,107,int64
Police Precinct,0,78,int64

Cell 10.5 — statistical summary of engineered numeric features

,mean,std,min,max
created_hour_sin,-0.1572,0.6672,-1.0000,1.0000
created_hour_cos,-0.1900,0.7028,-1.0000,1.0000
created_day_sin,0.0483,0.7003,-0.9749,0.9749
created_day_cos,0.0202,0.7119,-0.9010,1.0000
created_month_sin,0.8660,0.0000,0.8660,0.8660
created_month_cos,-0.5000,0.0000,-0.5000,-0.5000
created_is_business_hour,0.5089,0.4999,0.0000,1.0000
created_is_night,0.1044,0.3058,0.0000,1.0000
is_manhattan,0.2032,0.4024,0.0000,1.0000
is_brooklyn,0.2974,0.4571,0.0000,1.0000
is_queens,0.2537,0.4352,0.0000,1.0000
is_bronx,0.2056,0.4042,0.0000,1.0000
is_staten_island,0.0390,0.1937,0.0000,1.0000
distance_from_nyc_center,0.1273,0.0637,0.0001,0.3245
latitude_longitude_interaction,-3011.3167,5.9202,-3023.6155,-2993.4826
Agency_frequency,0.2603,0.1731,0.0001,0.4439
Agency Name_frequency,0.2603,0.1731,0.0001,0.4439
Problem (formerly Complaint Type)_frequency,0.0571,0.0568,0.0000,0.1624
Borough_frequency,0.2379,0.0564,0.0011,0.2974
Incident Zip_frequency,0.0079,0.0041,0.0000,0.0227
incident_zip_group_frequency,0.1971,0.0894,0.0000,0.3053
weekend_night_interaction,0.0387,0.1930,0.0000,1.0000
business_hour_weekday_interaction,0.3967,0.4892,0.0000,1.0000
borough_weekend_interaction,0.0608,0.1079,0.0000,0.2974
incident_zip_group_frequency,0.1971,0.0894,0.0000,0.3053
incident_zip_group_100,0.1952,0.3964,0.0000,1.0000
incident_zip_group_101,0.0038,0.0616,0.0000,1.0000
incident_zip_group_102,0.0009,0.0300,0.0000,1.0000
incident_zip_group_103,0.0387,0.1929,0.0000,1.0000
incident_zip_group_104,0.2052,0.4039,0.0000,1.0000
incident_zip_group_110,0.0018,0.0424,0.0000,1.0000
incident_zip_group_111,0.0379,0.1910,0.0000,1.0000
incident_zip_group_112,0.3053,0.4606,0.0000,1.0000
incident_zip_group_113,0.1163,0.3206,0.0000,1.0000
incident_zip_group_114,0.0838,0.2771,0.0000,1.0000
incident_zip_group_115,0.0000,0.0030,0.0000,1.0000
incident_zip_group_116,0.0110,0.1041,0.0000,1.0000
incident_zip_group_123,0.0000,0.0042,0.0000,1.0000
incident_zip_group_148,0.0000,0.0030,0.0000,1.0000
incident_zip_group_921,0.0000,0.0030,0.0000,1.0000

Cell 10.6 — train/test comparison for selected engineered features

,train_created_hour_sin,train_created_hour_cos,train_created_day_sin,train_created_day_cos,train_created_month_sin,train_created_month_cos,train_created_is_business_hour,train_created_is_night,train_is_manhattan,train_is_brooklyn,test_created_hour_sin,test_created_hour_cos,test_created_day_sin,test_created_day_cos,test_created_month_sin,test_created_month_cos,test_created_is_business_hour,test_created_is_night,test_is_manhattan,test_is_brooklyn
0,8.660254e-01,-0.500000,0.781831,0.623490,0.866025,-0.5,0,0,1,0,0.258819,-0.965926,0.433884,-0.900969,0.866025,-0.5,1,0,0,1
1,-7.071068e-01,-0.707107,0.433884,-0.900969,0.866025,-0.5,1,0,1,0,0.500000,-0.866025,-0.781831,0.623490,0.866025,-0.5,1,0,0,0
2,1.224647e-16,-1.000000,-0.781831,0.623490,0.866025,-0.5,1,0,0,1,0.866025,-0.500000,-0.433884,-0.900969,0.866025,-0.5,0,0,0,0
3,1.224647e-16,-1.000000,-0.433884,-0.900969,0.866025,-0.5,1,0,0,0,0.707107,-0.707107,0.000000,1.000000,0.866025,-0.5,1,0,0,1
4,7.071068e-01,-0.707107,0.433884,-0.900969,0.866025,-0.5,1,0,1,0,0.500000,-0.866025,0.781831,0.623490,0.866025,-0.5,1,0,1,0

Cell 10.7 — high correlation check between numerical features

,feature_1,feature_2,correlation
0,Agency_NYPD,Agency Name_New York City Police Department,1.0
1,is_bronx,Borough_BRONX,1.0
2,Borough_BROOKLYN,Park Borough_BROOKLYN,1.0
3,is_brooklyn,Park Borough_BROOKLYN,1.0
4,is_brooklyn,Borough_BROOKLYN,1.0
5,Borough_QUEENS,Park Borough_QUEENS,1.0
6,Agency_DEP,Agency Name_Department of Environmental Protec...,1.0
7,is_manhattan,Park Borough_MANHATTAN,1.0
8,Borough_MANHATTAN,Park Borough_MANHATTAN,1.0
9,is_manhattan,Borough_MANHATTAN,1.0
10,created_is_night,created_part_of_day_night,1.0
11,Agency_DCWP,Agency Name_Department of Consumer and Worker ...,1.0
12,Agency_DPR,Agency Name_Department of Parks and Recreation,1.0
13,Agency_NYC311-PRD,Agency Name_HIQA,1.0
14,Agency_HPD,Agency Name_Department of Housing Preservation...,1.0
15,Agency_EDC,Agency Name_Economic Development Corporation,1.0
16,Borough_BRONX,Park Borough_BRONX,1.0
17,is_queens,Park Borough_QUEENS,1.0
18,is_queens,Borough_QUEENS,1.0
19,Agency_DOT,Agency Name_Department of Transportation,1.0

X_train shape: (110930, 124)
y_train shape: (110930,)
X_test shape: (27733, 124)

In [5]:
# 2) basic feature quality check

feature_quality = pd.DataFrame({
    "missing_values": X_train.isna().sum(),
    "unique_values": X_train.nunique(),
    "dtype": X_train.dtypes.astype(str)
})

feature_quality = feature_quality.sort_values(
    "unique_values",
    ascending=True
)

print("features:", X_train.shape[1])
print("missing values in X_train:", X_train.isna().sum().sum())
print("non-numeric columns:", len(X_train.select_dtypes(exclude="number").columns))

display(feature_quality.head(20))

features: 124
missing values in X_train: 0
non-numeric columns: 0

,missing_values,unique_values,dtype
created_month_cos,0,1,float64
created_month_sin,0,1,float64
created_month,0,1,int32
Agency_TLC,0,2,int64
Open Data Channel Type_ONLINE,0,2,int64
Open Data Channel Type_MOBILE,0,2,int64
Borough_Unspecified,0,2,int64
Borough_STATEN ISLAND,0,2,int64
Borough_QUEENS,0,2,int64
Borough_MANHATTAN,0,2,int64
Borough_BROOKLYN,0,2,int64
Borough_BRONX,0,2,int64
Address Type_UNKNOWN,0,2,int64
Address Type_PLACENAME,0,2,int64
Address Type_PLACE,0,2,int64
Address Type_INTERSECTION,0,2,int64
Address Type_BLOCKFACE,0,2,int64
Address Type_ADDRESS,0,2,int64
Agency Name_Taxi and Limousine Commission,0,2,int64
Agency Name_Office of the Sheriff,0,2,int64

In [6]:
# 3) constant and near-constant features

near_constant_threshold = 0.99

constant_features = X_train.columns[
    X_train.nunique() <= 1
].tolist()

near_constant_features = []

for col in X_train.columns:
    most_common_ratio = X_train[col].value_counts(normalize=True).iloc[0]

    if most_common_ratio >= near_constant_threshold:
        near_constant_features.append(col)

near_constant_features = sorted(set(near_constant_features))

print("constant features:", len(constant_features))
print("near-constant features:", len(near_constant_features))

display(
    pd.DataFrame({
        "feature": near_constant_features
    }).head(30)
)

constant features: 3
near-constant features: 31

                                              feature
0                                  Address Type_PLACE
1                              Address Type_PLACENAME
2                                Address Type_UNKNOWN
3   Agency Name_Department of Consumer and Worker ...
4        Agency Name_Economic Development Corporation
5                                    Agency Name_HIQA
6     Agency Name_Office of Technology and Innovation
7                   Agency Name_Office of the Sheriff
8                                         Agency_DCWP
9                                          Agency_EDC
10                                  Agency_NYC311-PRD
11                                         Agency_OOS
12                                         Agency_OTI
13                                Borough_Unspecified
14                           Park Borough_Unspecified
15                     Park Facility Name_Forest Park
16                      Park Facility Name_Isham Park
17                  Park Facility Name_MacDonald Park
18  Park Facility Name_Sarah J.S. Tompkins Garnet ...
19                         Park Facility Name_UNKNOWN
20                     Park Facility Name_Unspecified
21                                      created_month
22                                  created_month_cos
23                                  created_month_sin
24                             incident_zip_group_101
25                             incident_zip_group_102
26                             incident_zip_group_110
27                             incident_zip_group_115
28                             incident_zip_group_123
29                             incident_zip_group_148

In [7]:
# 4) correlation check

correlation_threshold = 0.95

corr_matrix = X_train.corr(numeric_only=True).abs()

upper_triangle = corr_matrix.where(
    np.triu(
        np.ones(corr_matrix.shape),
        k=1
    ).astype(bool)
)

high_corr_pairs = (
    upper_triangle
    .stack()
    .sort_values(ascending=False)
    .reset_index()
)

high_corr_pairs.columns = [
    "feature_1",
    "feature_2",
    "correlation"
]

high_corr_pairs = high_corr_pairs[
    high_corr_pairs["correlation"] >= correlation_threshold
]

print("highly correlated feature pairs:", len(high_corr_pairs))

display(high_corr_pairs.head(30))

highly correlated feature pairs: 47

,feature_1,feature_2,correlation
0,Agency_NYPD,Agency Name_New York City Police Department,1.0
1,is_bronx,Borough_BRONX,1.0
2,Borough_BROOKLYN,Park Borough_BROOKLYN,1.0
3,is_brooklyn,Park Borough_BROOKLYN,1.0
4,is_brooklyn,Borough_BROOKLYN,1.0
5,Borough_QUEENS,Park Borough_QUEENS,1.0
6,Agency_DEP,Agency Name_Department of Environmental Protec...,1.0
7,is_manhattan,Park Borough_MANHATTAN,1.0
8,Borough_MANHATTAN,Park Borough_MANHATTAN,1.0
9,is_manhattan,Borough_MANHATTAN,1.0
10,created_is_night,created_part_of_day_night,1.0
11,Agency_DCWP,Agency Name_Department of Consumer and Worker ...,1.0
12,Agency_DPR,Agency Name_Department of Parks and Recreation,1.0
13,Agency_NYC311-PRD,Agency Name_HIQA,1.0
14,Agency_HPD,Agency Name_Department of Housing Preservation...,1.0
15,Agency_EDC,Agency Name_Economic Development Corporation,1.0
16,Borough_BRONX,Park Borough_BRONX,1.0
17,is_queens,Park Borough_QUEENS,1.0
18,is_queens,Borough_QUEENS,1.0
19,Agency_DOT,Agency Name_Department of Transportation,1.0
20,Agency_TLC,Agency Name_Taxi and Limousine Commission,1.0
21,Agency_DOHMH,Agency Name_Department of Health and Mental Hy...,1.0
22,Agency_frequency,Agency Name_frequency,1.0
23,Agency_OOS,Agency Name_Office of the Sheriff,1.0
24,Agency_OTI,Agency Name_Office of Technology and Innovation,1.0
25,Agency_DOB,Agency Name_Department of Buildings,1.0
26,Borough_STATEN ISLAND,Park Borough_STATEN ISLAND,1.0
27,is_staten_island,Park Borough_STATEN ISLAND,1.0
28,is_staten_island,Borough_STATEN ISLAND,1.0
29,Borough_Unspecified,Park Borough_Unspecified,1.0

In [8]:
# 5) choose correlated features to remove

features_to_remove_from_correlation = set()

for _, row in high_corr_pairs.iterrows():
    feature_1 = row["feature_1"]
    feature_2 = row["feature_2"]

    if feature_1 in features_to_remove_from_correlation:
        continue

    if feature_2 in features_to_remove_from_correlation:
        continue

    unique_1 = X_train[feature_1].nunique()
    unique_2 = X_train[feature_2].nunique()

    if unique_1 <= unique_2:
        features_to_remove_from_correlation.add(feature_1)
    else:
        features_to_remove_from_correlation.add(feature_2)

features_to_remove_from_correlation = sorted(
    features_to_remove_from_correlation
)

print("features selected for removal due to correlation:", len(features_to_remove_from_correlation))

display(
    pd.DataFrame({
        "feature": features_to_remove_from_correlation
    }).head(30)
)

features selected for removal due to correlation: 34

                       feature
0                  Agency_DCWP
1                   Agency_DEP
2                   Agency_DHS
3                   Agency_DOB
4                 Agency_DOHMH
5                   Agency_DOT
6                   Agency_DPR
7                  Agency_DSNY
8                   Agency_EDC
9                   Agency_HPD
10           Agency_NYC311-PRD
11                 Agency_NYPD
12                  Agency_OOS
13                  Agency_OTI
14                  Agency_TLC
15            Agency_frequency
16               Borough_BRONX
17            Borough_BROOKLYN
18           Borough_MANHATTAN
19              Borough_QUEENS
20       Borough_STATEN ISLAND
21         Borough_Unspecified
22          Park Borough_BRONX
23       Park Borough_BROOKLYN
24      Park Borough_MANHATTAN
25  Park Borough_STATEN ISLAND
26  Park Facility Name_UNKNOWN
27            created_is_night
28          created_is_weekend
29                    is_bronx

In [9]:
# 6) train/validation split for feature importance

X_train_part, X_valid_part, y_train_part, y_valid_part = train_test_split(
    X_train,
    y_train,
    test_size=0.20,
    random_state=42,
    stratify=y_train
)

print("X_train_part shape:", X_train_part.shape)
print("X_valid_part shape:", X_valid_part.shape)
print("y_train_part shape:", y_train_part.shape)
print("y_valid_part shape:", y_valid_part.shape)

X_train_part shape: (88744, 124)
X_valid_part shape: (22186, 124)
y_train_part shape: (88744,)
y_valid_part shape: (22186,)

In [10]:
# 7) feature importance from baseline model

importance_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=12,
    min_samples_leaf=20,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)

importance_model.fit(
    X_train_part,
    y_train_part
)

valid_predictions = importance_model.predict(X_valid_part)

valid_accuracy = accuracy_score(
    y_valid_part,
    valid_predictions
)

print("validation accuracy of feature-importance model:", round(valid_accuracy, 4))

validation accuracy of feature-importance model: 0.8698

In [11]:
# 8) display feature importance

feature_importance = pd.DataFrame({
    "feature": X_train.columns,
    "importance": importance_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    "importance",
    ascending=False
)

display(feature_importance.head(30))

                                              feature  importance
38                                   Agency_frequency    0.172769
39                              Agency Name_frequency    0.160774
73        Agency Name_New York City Police Department    0.135132
58                                        Agency_NYPD    0.093010
40        Problem (formerly Complaint Type)_frequency    0.064339
2                                  Additional Details    0.049043
3                                       Location Type    0.043734
0                   Problem (formerly Complaint Type)    0.032969
9                               Intersection Street 1    0.028757
67  Agency Name_Department of Housing Preservation...    0.024237
56                                         Agency_HPD    0.023488
12                                           Landmark    0.016233
10                              Intersection Street 2    0.015533
1                Problem Detail (formerly Descriptor)    0.014529
8                                      Cross Street 2    0.009900
7                                      Cross Street 1    0.009114
49                                         Agency_DHS    0.005445
89                      Open Data Channel Type_MOBILE    0.004851
69               Agency Name_Department of Sanitation    0.004816
54                                        Agency_DSNY    0.004510
66        Agency Name_Department of Homeless Services    0.004451
52                                         Agency_DOT    0.004038
24                                   created_hour_cos    0.003915
92                     Open Data Channel Type_UNKNOWN    0.003789
50                                         Agency_DOB    0.003744
70           Agency Name_Department of Transportation    0.003693
91                       Open Data Channel Type_PHONE    0.003676
5                                    Incident Address    0.003403
16                                                BBL    0.002701
36                           distance_from_nyc_center    0.002406

In [12]:
# 9) select final features

zero_importance_features = (
    feature_importance[
        feature_importance["importance"] == 0
    ]["feature"]
    .tolist()
)

features_to_remove = sorted(
    set(near_constant_features)
    | set(features_to_remove_from_correlation)
    | set(zero_importance_features)
)

selected_features = [
    col for col in X_train.columns
    if col not in features_to_remove
]

print("original features:", X_train.shape[1])
print("features removed:", len(features_to_remove))
print("selected features:", len(selected_features))

removed_features_summary = pd.DataFrame({
    "feature": features_to_remove
})

display(removed_features_summary.head(40))

original features: 124
features removed: 58
selected features: 66

                                              feature
0                                  Address Type_PLACE
1                              Address Type_PLACENAME
2                                Address Type_UNKNOWN
3   Agency Name_Department of Consumer and Worker ...
4        Agency Name_Economic Development Corporation
5                                    Agency Name_HIQA
6     Agency Name_Office of Technology and Innovation
7                   Agency Name_Office of the Sheriff
8                                         Agency_DCWP
9                                          Agency_DEP
10                                         Agency_DHS
11                                         Agency_DOB
12                                       Agency_DOHMH
13                                         Agency_DOT
14                                         Agency_DPR
15                                        Agency_DSNY
16                                         Agency_EDC
17                                         Agency_HPD
18                                  Agency_NYC311-PRD
19                                        Agency_NYPD
20                                         Agency_OOS
21                                         Agency_OTI
22                                         Agency_TLC
23                                   Agency_frequency
24                                      Borough_BRONX
25                                   Borough_BROOKLYN
26                                  Borough_MANHATTAN
27                                     Borough_QUEENS
28                              Borough_STATEN ISLAND
29                                Borough_Unspecified
30                                 Park Borough_BRONX
31                              Park Borough_BROOKLYN
32                             Park Borough_MANHATTAN
33                         Park Borough_STATEN ISLAND
34                           Park Borough_Unspecified
35                     Park Facility Name_Forest Park
36                      Park Facility Name_Isham Park
37                  Park Facility Name_MacDonald Park
38  Park Facility Name_Sarah J.S. Tompkins Garnet ...
39                         Park Facility Name_UNKNOWN

In [13]:
# 10) create selected datasets

X_train_selected = X_train[selected_features].copy()
X_test_selected = X_test[selected_features].copy()

assert X_train_selected.shape[1] == X_test_selected.shape[1]
assert X_train_selected.isna().sum().sum() == 0
assert X_test_selected.isna().sum().sum() == 0
assert len(X_train_selected.select_dtypes(exclude="number").columns) == 0
assert len(X_test_selected.select_dtypes(exclude="number").columns) == 0

print("X_train_selected shape:", X_train_selected.shape)
print("y_train shape:", y_train.shape)
print("X_test_selected shape:", X_test_selected.shape)

X_train_selected shape: (110930, 66)
y_train shape: (110930,)
X_test_selected shape: (27733, 66)

In [14]:
# 11) final visual checks

selection_summary = pd.DataFrame({
    "step": [
        "original features",
        "near-constant features removed",
        "correlated features removed",
        "zero-importance features removed",
        "final selected features"
    ],
    "count": [
        X_train.shape[1],
        len(near_constant_features),
        len(features_to_remove_from_correlation),
        len(zero_importance_features),
        len(selected_features)
    ]
})

display(selection_summary)

print("top selected features by importance")

display(
    feature_importance[
        feature_importance["feature"].isin(selected_features)
    ].head(30)
)

print("preview of selected training features")

display(X_train_selected.head().T)

                               step  count
0                 original features    124
1    near-constant features removed     31
2       correlated features removed     34
3  zero-importance features removed     18
4           final selected features     66

top selected features by importance

                                              feature  importance
39                              Agency Name_frequency    0.160774
73        Agency Name_New York City Police Department    0.135132
40        Problem (formerly Complaint Type)_frequency    0.064339
2                                  Additional Details    0.049043
3                                       Location Type    0.043734
0                   Problem (formerly Complaint Type)    0.032969
9                               Intersection Street 1    0.028757
67  Agency Name_Department of Housing Preservation...    0.024237
12                                           Landmark    0.016233
10                              Intersection Street 2    0.015533
1                Problem Detail (formerly Descriptor)    0.014529
8                                      Cross Street 2    0.009900
7                                      Cross Street 1    0.009114
89                      Open Data Channel Type_MOBILE    0.004851
69               Agency Name_Department of Sanitation    0.004816
66        Agency Name_Department of Homeless Services    0.004451
24                                   created_hour_cos    0.003915
92                     Open Data Channel Type_UNKNOWN    0.003789
70           Agency Name_Department of Transportation    0.003693
91                       Open Data Channel Type_PHONE    0.003676
5                                    Incident Address    0.003403
16                                                BBL    0.002701
36                           distance_from_nyc_center    0.002406
76          Agency Name_Taxi and Limousine Commission    0.002355
18                                          Longitude    0.002151
6                                         Street Name    0.002047
62                Agency Name_Department of Buildings    0.001991
15                                    Police Precinct    0.001938
37                     latitude_longitude_interaction    0.001929
77                               Address Type_ADDRESS    0.001903

preview of selected training features

,0,1,2,3,4
Problem (formerly Complaint Type),64.0,64.0,74.0,122.0,45.0
Problem Detail (formerly Descriptor),193.0,2.0,499.0,695.0,406.0
Additional Details,331.0,331.0,529.0,529.0,363.0
Location Type,66.0,66.0,81.0,101.0,66.0
Incident Zip,10011.0,10025.0,11238.0,10453.0,10016.0
...,...,...,...,...,...
incident_zip_group_111,0.0,0.0,0.0,0.0,0.0
incident_zip_group_112,0.0,0.0,1.0,0.0,0.0
incident_zip_group_113,0.0,0.0,0.0,0.0,0.0
incident_zip_group_114,0.0,0.0,0.0,0.0,0.0
incident_zip_group_116,0.0,0.0,0.0,0.0,0.0

In [15]:
# The first section imports the required libraries and checks that X_train, y_train, and X_test are available
# from the previous preprocessing and feature engineering notebook.
#
# The second section performs a basic quality check on the features, including missing values, data types,
# and the number of unique values for each feature.
#
# The third section identifies constant and near-constant features, which are unlikely to help the model
# because they contain little or no variation.
#
# The fourth section checks for highly correlated numerical features. Strongly correlated features may provide
# redundant information and can make the model more complex.
#
# The fifth section selects which correlated features should be removed, keeping one feature from each highly
# correlated pair.
#
# The sixth section creates an internal train-validation split using only the training data. This split is used
# only to estimate feature importance and does not involve the test set.
#
# The seventh section trains a Random Forest model on the internal training split to estimate feature importance.
#
# The eighth section displays the most important features according to the baseline Random Forest model.
#
# The ninth section combines the feature selection rules and creates the final list of selected features.
# It removes near-constant features, redundant correlated features, and features with zero model importance.
#
# The tenth section creates X_train_selected and X_test_selected using the same selected feature columns.
# The test set is not used to decide which features to keep; it is only filtered using the choices made from
# the training data.
#
# The eleventh section displays a final summary of the feature selection process and previews the selected
# training features.